name: Publish Image

on:
  push:

env:
 REGISTRY: registry.cn-hangzhou.aliyuncs.com

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASS }}
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch
      - name: Build and push Docker image
        run: |
          docker build --build-arg VERSION="${{ steps.extract_branch.outputs.branch }}" . --file Dockerfile --tag ${{ env.REGISTRY }}/goldenimage/ansible:${{ steps.extract_branch.outputs.branch }}
          docker push ${{ env.REGISTRY }}/goldenimage/ansible:${{ steps.extract_branch.outputs.branch }}
      - name: Wechat Work action
        uses: wertycn/work-wechat-send-action@main
        with:
          wechat_id: ${{ secrets.WECHAT_COMPANY_ID }}
          agent_secret: ${{ secrets.WECHAT_APP_SECRET }}
          agent_id: 1000003
          to_user: @all
          msgtype: text
          send_step: main
          content: |
            ## action test
            > from github action test
            - repository: ${{ github.repository }}
            - committer: ${{ github.actor }}
            - compare: [view](${{ github.event.compare }})
            - job status: ${{ job.status }}